<?php

namespace AppBundle\Repository;

/**
 * MateriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriasRepository extends \Doctrine\ORM\EntityRepository
{
}
